#!/bin/sh
uci set wireless.@wifi-device[0].country='US'
uci set wireless.@wifi-device[0].txpower='25'
uci set wireless.@wifi-device[1].country='US'
uci set wireless.@wifi-device[1].txpower='24'
uci commit wireless
wifi reload
